### ISSUE TITLE
Broken script, fails to browse internet archive

### ISSUE THREAD

**Issue by mehmetaergun** [divingmule/plugin.audio.internet.archive#1]
I get the following in my kodi.log (14, Helix) when I try to go/click on InternetArchive -> Audio Archive and  same for InternetArchive -> Video Archive

```
20:05:01 T:1492616256  NOTICE: Thread JobWorker start, auto delete: true
20:05:01 T:1477440576  NOTICE: Thread LanguageInvoker start, auto delete: false
20:05:01 T:1477440576  NOTICE: -->Python Interpreter Initialized<--
20:05:31 T:1477440576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.internet.archive/default.py", line 533, in <module>
                                                get_category_page(params['url'], params['iconimage'])
                                              File "/storage/.kodi/addons/plugin.audio.internet.archive/default.py", line 97, in get_category_page
                                                collection_tag = soup.find('select', attrs={'name': 'mediatype'}).find('option', selected='selected')
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
20:05:32 T:1969988128   ERROR: GetDirectory - Error getting plugin://plugin.audio.internet.archive/?iconimage=http%3a%2f%2fia600304.us.archive.org%2f25%2fitems%2faudio%2faudi
o.gif&mode=get_category_page&name=Audio%20Archive&url=http%3a%2f%2fwww.archive.org%2fdetails%2faudio                                                                         
20:05:32 T:1969988128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.internet.archive/?iconimage=http%3a%2f%2fia600304.us.archive.org%2f25%2fitems%2faudio%2faud
io.gif&mode=get_category_page&name=Audio%20Archive&url=http%3a%2f%2fwww.archive.org%2fdetails%2faudio) failed                                                                
20:05:32 T:1477440576  NOTICE: Thread BackgroundLoader start, auto delete: false
```

**Comment by jessebikman** [comment]
MetalChris has resolved these issues in his updated plugin - add them as custom plugins and it should work for you:

https://github.com/MetalChris/repository.metalchris/tree/master/plugin.video.internetarchive

https://github.com/MetalChris/repository.metalchris/tree/master/plugin.audio.internet-radio

**Comment by petterreinholdtsen** [comment]
I just tested the Internet Archive add-on, and it failed for me.  I get a message stating "Internet Archive error\nCheck the log for more information."

In /storage/.kodi/temp/kodi.log I find these lines that seem relevant:

```
22:25:09.469 T:1306964896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback
/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 
'find'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.internet
.archive/default.py", line 526, in <module>
                                                get_category_page(video_url, video_thumb)
                                              File "/storage/.kodi/addons/plugin.audio.internet
.archive/default.py", line 97, in get_category_page
                                                collection_tag = soup.find('select', attrs={'na
me': 'mediatype'}).find('option', selected='selected')
                                            AttributeError: 'NoneType' object has no attribute 
'find'
                                            -->End of Python script error report<--
22:25:09.629 T:1947152400   ERROR: GetDirectory - Error getting plugin://plugin.audio.internet.
archive/?content_type=video
22:25:09.630 T:1947152400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.internet
.archive/?content_type=video) failed
```

Any hope to get a working add-on automatically in a recent kodi install?

**Comment by divingmule** [comment]
Hi all,
I never had the time/motivation to up date this add-on. Luckily, @MetalChris picked it up.

Check out https://github.com/MetalChris or look him up on the [Kodi Fourm](https://forum.kodi.tv/)

**Comment by petterreinholdtsen** [comment]
[divingmule]
> Hi all,
> I never had the time/motivation to up date this add-on. Luckily,
> @MetalChris picked it up.

Aha.  Yours is still the one pointed to by 
<URL: https://kodi.wiki/view/Add-on:Internet_Archive >, and as far as I
can tell, it is the one I got when adding the Internet Archive add-on
from within kodi.

Thus most users will end up with your add-on unless something is changed
centrally.

> Check out https://github.com/MetalChris or look him up on the [Kodi
> Fourm](https://forum.kodi.tv/)

Found it in <URL: https://github.com/MetalChris/repository.metalchris >.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
In https://github.com/MetalChris/repository.metalchris/issues/34 @MetalChris report that he do not plan to update the official Kodi repository.

**Comment by petterreinholdtsen** [comment]
I had the incorrect idea that @MetalChris had started with this add-on and modified it to his liking, but after looking at the code of plugin.audio.internetarchive and plugin.video.internetarchive, I conclude that they are completely different from this code base and was probably rewritten from scratch.

I had hoped to be able to create a pull request with his changes to get them into this repository, but if I tried it would be a complete rewrite.  Are you interested in accepting such pull request?
